[package]
name = "aunsorm-acme"
version = "0.4.2"
edition = "2021"
license = "Apache-2.0"
description = "ACME protocol primitives for the Aunsorm security suite"
readme = "README.md"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = "1"
